services:
  - type: web
    name: pinguim-filmes
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PINGUIM_SECRET_KEY
        generateValue: true
      - key: TMDB_API_KEY
        value: 0cc6bfd91cbdb1775b79fd4267b9e3c2
      - key: TMDB_READ_TOKEN
        value: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwY2M2YmZkOTFjYmRiMTc3NWI3OWZkNDI2N2I5ZTNjMiIsIm5iZiI6MTc3NjMxMDY5MS4zMTIsInN1YiI6IjY5ZTA1OWEzNDEzMDRhMzRkZDM5NGExMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.vaGx7CG_gCVlpm9niMwMkuw4nsiGVxYCGUhkEa7yTfw
    disk:
      name: pinguim-db
      mountPath: /opt/render/project/src
      sizeGB: 1
