services:
  - type: web
    name: medflix
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SETUP_CODE
        value: medflix2026
    disk:
      name: medflix-db
      mountPath: /opt/render/project/src
      sizeGB: 1
